# Generated by Django 5.2rc1 on 2025-04-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0002_hobby_remove_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
