# Generated by Django 5.1.7 on 2025-04-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0008_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZodiacSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название знака')),
            ],
        ),
    ]
