# Generated by Django 5.1.7 on 2025-04-15 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0009_zodiacsign'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='zodiac_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.zodiacsign', verbose_name='Знак зодиака'),
        ),
    ]
