# Generated by Django 5.1.7 on 2025-04-15 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0010_userprofile_zodiac_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Уровень образования')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.education', verbose_name='Образование'),
        ),
    ]
