# Generated by Django 5.1.7 on 2025-04-19 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0011_education_userprofile_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='HobbyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
            ],
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='hobby',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.hobbygroup', verbose_name='Группа'),
        ),
    ]
