# Generated by Django 5.1.7 on 2025-04-19 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0012_hobbygroup_alter_hobby_name_hobby_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.education')),
                ('hobbies', models.ManyToManyField(blank=True, to='lk.hobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zodiac_sign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.zodiacsign')),
            ],
        ),
    ]
