# Generated by Django 5.1.7 on 2025-04-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0013_userfilters'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
