# Generated by Django 5.1.7 on 2025-04-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0015_alter_userprofile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, 'Мужской'), (2, 'Женский')], default=1, null=True, verbose_name='Пол'),
        ),
    ]
