# Generated by Django 5.1.7 on 2025-04-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0017_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='user_photos/photo_base.jpg', null=True, upload_to='user_photos/'),
        ),
    ]
