# Generated by Django 5.1.7 on 2025-04-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0018_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_CR',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weights_for_ahp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
