# Generated by Django 5.1.7 on 2025-04-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0019_userprofile_user_cr_userprofile_weights_for_ahp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city_vs_education',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city_vs_hobby',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city_vs_zodiac',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_vs_hobby',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_vs_zodiac',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobby_vs_zodiac',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
