# Generated by Django 5.1.7 on 2025-05-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0023_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hide_age',
            field=models.BooleanField(default=False, verbose_name='Скрыть возраст'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hide_character',
            field=models.BooleanField(default=False, verbose_name='Скрыть характер'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hide_children',
            field=models.BooleanField(default=False, verbose_name='Скрыть информацию о детях'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hide_city',
            field=models.BooleanField(default=False, verbose_name='Скрыть город'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hide_education',
            field=models.BooleanField(default=False, verbose_name='Скрыть образование'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hide_hobbies',
            field=models.BooleanField(default=False, verbose_name='Скрыть хобби'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hide_hobby_description',
            field=models.BooleanField(default=False, verbose_name='Скрыть описание хобби'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hide_life_goal',
            field=models.BooleanField(default=False, verbose_name='Скрыть цель в жизни'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hide_zodiac',
            field=models.BooleanField(default=False, verbose_name='Скрыть знак зодиака'),
        ),
    ]
