# Generated by Django 5.1.7 on 2025-04-27 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_receiver'),
        ('lk', '0020_userprofile_city_vs_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair_room',
            name='user1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user1_rooms', to='lk.userprofile'),
        ),
        migrations.AddField(
            model_name='pair_room',
            name='user2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user2_rooms', to='lk.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='pair_room',
            unique_together={('user1', 'user2')},
        ),
    ]
