# Generated by Django 5.1.7 on 2025-05-02 18:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_pair_room_user1_pair_room_user2_and_more'),
        ('lk', '0022_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='lk.userprofile'),
        ),
        migrations.AlterField(
            model_name='pair_room',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_rooms', to='lk.userprofile'),
        ),
        migrations.AlterField(
            model_name='pair_room',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_rooms', to='lk.userprofile'),
        ),
    ]
