version: '3.5'
services:
  db:
    container_name: db
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      DB_NAME: tinder
      POSTGRES_PASSWORD: 14881337
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"
